# Generated by Django 4.0 on 2021-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_contact_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Status',
            field=models.CharField(choices=[('UC', 'Unclaimed'), ('CL', 'Claimed'), ('CD', 'Closed')], default='UC', max_length=2),
        ),
    ]
