# Generated by Django 4.0 on 2021-12-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Status',
            new_name='status',
        ),
    ]
