# Generated by Django 4.0 on 2021-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_status_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='by_call',
            field=models.BooleanField(default=False),
        ),
    ]
